spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartcycle
    username: smartcycle
    password: smartcycle

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

server:
  port: 8080
